### PR TITLE
Update TensorFlow API to 0.12.0

### PR DESCRIPTION
**Pull request by futurely**
Fix the errors running with TensorFlow 0.12.0/1.

### CODE REVIEW

**Comment by tlbtlbtlb** [comment]
This doesn't work at all on tf 0.11. Do we really want to break that?

**Comment by tlbtlbtlb** [comment]
@rafaljozefowicz If you're going to break tf 0.11, update the README to require tf 0.12.

**Comment by rafaljozefowicz** [comment]
Thanks @tlbtlbtlb I missed that. Is there a reason to support older version? The older interface will likely stop working with future TF releases anyway.

**Comment by tlbtlbtlb** [comment]
Just that some people have it installed, and they'll be confused. 
It didn't work with 0.12 either, but I checked in a fix

**Comment by tlbtlbtlb** [comment]
I reverted this, because it doesn't work and fixing the obvious bugs hasn't fixed it. I created a branch called tf12 for people that want to experiment

**Pull request merged**
