### PR TITLE
Updated model.py to use new reference for tensorboard rnn methods.

### PR DESCRIPTION
**Pull request by MatthewSBarnes**
## Before
Workers Output:
image

### CODE REVIEW

**Comment by tlbtlbtlb** [comment]
I assume you're using tf 1.0? Unfortunately this breaks in tf 0.11 and 0.12 (the versions recommended on the README page).

**Comment by MatthewSBarnes** [comment]
Oh I see! That makes sense. 
Are there plans to update to tf 1.0 any time soon?

If you'd like to close this PR, please do!

**Comment by tlbtlbtlb** [comment]
Ideally, handle it the same way as the 0.11 / 0.12 change. Grep for 'use_tf12_api' and add a 'use_tf100_api' flag.

**Comment by tlbtlbtlb** [comment]
Thanks!

**Pull request merged**
