### PR TITLE
Option to add '--visualise' when running train.py or worker.py which uses the built in env.render()

### PR DESCRIPTION
**Pull request by brtknr**

### CODE REVIEW

**Comment by yaroslavvb** [comment]
@tlbtlbtlb is there some semi-automated testing thing for starter agent now?

**Comment by brtknr** [comment]
I could not find any apart from using the VNC server. But an agent trained on standard pong environment doesn't work well with vnc-pong. Therefore, with this fix, it allows the standard pong environment to be visualised.

**Comment by tlbtlbtlb** [comment]
LGTM.
@yaroslavvb There is automated testing 4x daily on the master branch (it burns 100 core-hours per test, so I don't do it on PRs yet but maybe I should.)

**Comment by ethancaballero** [comment]
When running train.py with visualize script on macbook, python rocketship(s) appear in Dock, but they say "Appplication Not Repsonding" and no render window appears.

**Comment by brtknr** [comment]
Have you logged into tmux session and looked at what the worker logs say?

Does it work without the visualise toggle?

**Comment by brtknr** [comment]
Tbf, this has currently only been tested on an Ubuntu 16.04 desktop
machine. Can you also post what version of python you're using as well as
openai gym+universe packages?

**Pull request merged**
