### PR TITLE
GRU-A3C

### PR DESCRIPTION
**Pull request by louiehelm**
I'm getting positive results by replacing LSTMs --> GRUs in your A3C implementation.

Wrote up a short report:
https://github.com/louiehelm/universe-starter-agent/blob/gru/README.md

I know the starter agent is a reference design, so you may not want to include every possible improvement.

OTOH, switching to GRUs makes the code shorter, avoids creating an extra tuple, removes two transposes per pass, runs at higher throughput, and seems to be generally dominant vs LSTMs for every environment I've tested so far.

I know my own research cycles are much faster with this version and data-efficiency is up a lot, which makes trying new ideas way easier.

### CODE REVIEW

**Comment by tlbtlbtlb** [comment]
Looks great!
We can't just merge this, because it overwrites the README with a discussion of the differences rather than the gentle introduction to agent training that a starter-kit should have. But I recommend anyone experimenting with training to try this!

**Comment by crci** [comment]
@louiehelm looks great. Since the neonracer is the other reference game in this repo, have you tried it on that one? If so, what results did you get and with what hyperparameters?

**Comment by tlbtlbtlb** [comment]
Is there a reference for how Nadam differs from Adam?

The documentation says they do the same thing:
https://github.com/tensorflow/tensorflow/blob/86d3891ba6612552347beaabe27edac11f5758d7/tensorflow/core/ops/training_ops.cc#L1767
https://github.com/tensorflow/tensorflow/blob/d5a93567547d77ae2682b55170a3c7a28cfce6f8/tensorflow/core/ops/training_ops.cc#L1139

Although I can see the momentum calculation adds a soft-start:
https://github.com/tensorflow/tensorflow/blob/86d3891ba6612552347beaabe27edac11f5758d7/tensorflow/core/kernels/training_ops_gpu.cu.cc#L187
https://github.com/tensorflow/tensorflow/blob/86d3891ba6612552347beaabe27edac11f5758d7/tensorflow/core/kernels/training_ops_gpu.cu.cc#L117

**Comment by louiehelm** [comment]
Nadam:  Google is debating between multiple Nadam implementations. Mine has a lot of C++, works like all their other optimizers, and is very fast so they pulled it in initially. But it's a lot of lines of very similar code to what exists in other places, so they may go with a python-only version that has some compelling maintenance benefits. For now, they don't have anyone's Nadam pulled into TF HEAD. See https://github.com/tensorflow/tensorflow/pull/9175#issuecomment-294014551

The adventurous can still pull the branch you've linked to. Although, I've reverted this PR to Adam for now since it works fine for evaluating GRU changes. Nadam is better in general, but I was mainly just trying to get more eyes on the new TF optimizer since I want others to start using it over Adam once it's available.

GRU: I ran some NeonRace tests on my laptop (CPU).

6 agents hitting 35k scores after 100k steps (1hr). Results are in line with current LSTM implementation or perhaps a bit better. Major difference w/ GRU is a stronger score upswing before 100k, which happens ~10k steps sooner (and the CPUs were less crushed by 6 GRU agents vs 6 LSTM agents).

Should I craft a single feature PR that isolates these model changes to just replace LSTM with GRUs?

**Pull request closed without merging**
